-- Add company information fields to tenants table
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "industry" VARCHAR(100);
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "company_size" VARCHAR(50);
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "founded_year" INTEGER;
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "tax_id" VARCHAR(50);
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "phone" VARCHAR(30);
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "email" VARCHAR(255);
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "website" VARCHAR(255);
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "address" VARCHAR(255);
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "city" VARCHAR(100);
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "state" VARCHAR(100);
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "country" VARCHAR(100);
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "postal_code" VARCHAR(20);
